version: '3.4'

services:
  myblazorserver:
    image: ${DOCKER_REGISTRY-}myblazorserver
    build:
      context: .
      dockerfile: MyBlazorServer.Dotnet5/Dockerfile
    container_name: myblazorserver
